### ISSUE TITLE
Add "old" or "deprecated" tags to tutorials

### ISSUE THREAD

**Issue by bilgeyucel** [deepset-ai/haystack-home#127]
We'll remove some components from Haystack. Tutorials with these components should have a tag to indicate this deprecation.

```[tasklist]
### Tasks
- [x] Decide on the name
- [x] Request a tag implementation from Carlos
- [x] Update haystack-tutorials `generate` scripts to produce the suitable frontmatter
- [x] Tag related tutorials
```

**Comment by bilgeyucel** [comment]
`works with v1.16` sounds great. My only concern is the length of the text. It will always cause tags to overflow to the second line
![image](https://github.com/deepset-ai/haystack-home/assets/25897116/194ea73a-5d55-4297-8243-98c93a243e42)

Now that I have started thinking about it, adding this tag to tutorials is a bit counterintuitive as it might sound like others are not working with `v1.16`.  How about changing the name to "works up till v1.16"?

Another point is, which is totally UI related, the color of the tag. We have already added a tag when a tutorial is "featured", so to draw attention. The purpose of this tag, however, is contrary, to avoid drawing attention to these tutorials. Should we leave the color to Carlos or do you have any other ideas?

**Comment by TuanaCelik** [comment]
'compatible up to v1.16'? 
As for the length, a suggestion would be to have the full line once you go to the tutorial but on the card it can simply be a version tag with the Haystack logo next to it, and have the line come up on hover saying the full 'works with' or 'compatible up to'?

I'm sure we can find some good practices out there. Shall we do some field research?

**Comment by masci** [comment]
@TuanaCelik now that you mentioned it in your comment, what about "outdated"?

**Comment by bilgeyucel** [comment]
"Outdated" can give the message in the tutorial card. We can add a longer text in the tutorial content as "compatible up to v1.16". We already add a note on top of the tutorial so it should be fine

![image](https://github.com/deepset-ai/haystack-home/assets/25897116/2f2c3411-1589-4776-81c9-8006456e4c55)


In the outdated tutorials, we pin the version as we install Haystack like `pip install farm-haystack[colab,inmemorygraph]==1.16.0`. So it should be easy to set and maintain the versions, but I might be missing a point.

**Comment by TuanaCelik** [comment]
I think we have an agreement :) I like 'outdated' on the card + this type of warning in the tutorial as @bilgeyucel mentions

**Comment by bilgeyucel** [comment]
Then, we can introduce a new `haystack_version` key to the frontmatter of the tutorial. If the value isn't `"latest"`, we display the "outdated" tag. We can use this `haystack_version` as we test the tutorials so it's better to have a multifunctional variable rather than a boolean key.
